### ISSUE TITLE
troubles with pod 2.9.1

### ISSUE THREAD

**Issue by cperves** [EsupPortail/moodle-repository_pod#11]
* When migrating to pod 2.9.1 there seems to have troubles with moodle player and pod videos
* viedeo not seems to be loaded
* player error : 
```
Failed to load resource: net::ERR_UNEXPECTED_PROXY_AUTH
```
Trouble given by Ronan Apriou

**Comment by Gael-Mifsud** [comment]
Hello,

Our POD has migrate to version 2.9.1 Wednesday March the second.

Since then, the repository is still available, but the videos don't play anymore.
The play button is greyed.

We find this in Moodle logfile :
```
[Mon Mar 07 10:50:10.133254 2022] AH01071: Got error 'PHP message: Default exception handler: repository/podfilenotfound Debug: \n
Error code: podfilenotfound\n
$a contents: Fichier pod non trouv\xc3\xa9.\n
* line 176 of /repository/pod/lib.php: repository_exception thrown\n
* line 1045 of /lib/filestorage/stored_file.php: call to repository_pod->send_file()\n
* line 2709 of /lib/filelib.php: call to stored_file->send_file()\n
* line 5065 of /lib/filelib.php: call to send_stored_file()\n
* line 44 of /pluginfile.php: call to file_pluginfile()\n', referer: https://moodle.univ-lille.fr/course/view.php?id=10439
```

**Comment by ptitloup** [comment]
hello, 
it's seems to be from Pod. here is the log found : 

> Internal Server Error: /rest/encodings_video/video_encodedfiles/
> 
> TypeError at /rest/encodings_video/video_encodedfiles/
> Object of type ManyRelatedManager is not JSON serializable
> 
> Request Method: GET
> Request URL: https://pod.univ-lille.fr/rest/encodings_video/video_encodedfiles/?&format=json&video=607&extension=mp4
> Django Version: 1.11.29
> Python Executable: /usr/local/bin/uwsgi

I will check it in dev branch and will fix it if it's necessary

**Comment by cperves** [comment]
@ptitloup , thanks
If necessary i'll check Moodle part if it not comes from pod
I'll wait your conclusions

**Comment by ptitloup** [comment]
ok, I fixed it in dev branch : https://github.com/EsupPortail/Esup-Pod/pull/594
can you test this and tell me if it's ok for you ten i will push it in prod

**Comment by cperves** [comment]
I try on my dev instance
may @Gael-Mifsud test also?
Thx
Céline

**Comment by cperves** [comment]
all my pod resources in direct mod (not enriched) works on my dev instance
enriched one works also
for information search works well too

**Comment by ptitloup** [comment]
ok thx for yours feedback, I will put it in master asap

**Comment by cperves** [comment]
may be wait for Gaël returns, I have contacted Ronan to confirm if it is now OK

**Comment by ptitloup** [comment]
ok Gael and I just check the repository on our test instance of Moodle and all is ok for us.
I 'll merge it in master
Thx !

**Comment by cperves** [comment]
Thank you very much!

**Comment by ptitloup** [comment]
Done !

**Comment by cperves** [comment]
What an effective collaboration:
* final user as reporter and tester
* Moodle and pod devs

Thx you all
